# This is script to build hmdbMsTb from HMDB 5.0
# https://hmdb.ca/downloads
# Barry Song

# library(magrittr)
# setwd("G:/spd/Projects/2024/pubmsR/Progress/experiments/build_hmdbMsTb/")
experiment_xml_files_name <- list.files("G:/spd/Projects/2024/pubmsR/Data/HMDB/hmdb_experimental_msms_spectra/")
prediction_xml_files_name <- list.files("G:/spd/Projects/2024/pubmsR/Data/HMDB/hmdb_predicted_msms_spectra/")
# experiment_xml_files_name <- readRDS("G:/spd/Projects/2024/pubmsR/Data/HMDB/experiment_xml_files_name.rds")
# prediction_xml_files_name <- readRDS("G:/spd/Projects/2024/pubmsR/Data/HMDB/prediction_xml_files_name.rds")
experiment_xml_files_path <- paste0("G:/spd/Projects/2024/pubmsR/Data/HMDB/hmdb_experimental_msms_spectra/", experiment_xml_files_name)
prediction_xml_files_path <- paste0("G:/spd/Projects/2024/pubmsR/Data/HMDB/hmdb_predicted_msms_spectra/", prediction_xml_files_name)

dfList_experiment <- lapply(1:length(experiment_xml_files_path), function(i) {
  print(paste0(i, " / ", length(experiment_xml_files_path)))
  pubmsR:::.read_hmdb_xml(xml_path = experiment_xml_files_path[i])
})
df_experiment <- purrr::list_rbind(dfList_experiment)
# saveRDS(df_experiment, file = "df_experiment.rds")

dfList_prediction <- lapply(1:length(prediction_xml_files_path), function(i) {
  print(paste0(i, " / ", length(prediction_xml_files_path)))
  pubmsR:::.read_hmdb_xml(xml_path = prediction_xml_files_path[i])
})
df_prediction <- purrr::list_rbind(dfList_prediction)
# saveRDS(df_prediction, file = "df_prediction.rds")

df_all <- rbind(df_experiment, df_prediction)
df_all$id <- as.integer(df_all$id)

hmdbMsTb <- df_all %>%
  dplyr::arrange(id) %>%
  dplyr::as_tibble() %>%
  dplyr::filter(!is.na(mz) & !is.na(int))
hmdbMsTb[hmdbMsTb == ""] <- NA
saveRDS(hmdbMsTb, file = "hmdbMsTb.rds")

unique(df_experiment$id)
unique(df_prediction$id)
unique(df_experiment$notes)
unique(df_prediction$notes)
unique(df_experiment$sample_concentration)
unique(df_prediction$sample_concentration)
unique(df_experiment$solvent)
unique(df_prediction$solvent)
unique(df_experiment$sample_mass)
unique(df_prediction$sample_mass)
unique(df_experiment$sample_assessment)
unique(df_prediction$sample_assessment)
unique(df_experiment$spectra_assessment)
unique(df_prediction$spectra_assessment)
unique(df_experiment$sample_source)
unique(df_prediction$sample_source)
unique(df_experiment$collection_date)
unique(df_prediction$collection_date)
unique(df_experiment$instrument_type)
unique(df_prediction$instrument_type)
unique(df_experiment$peak_counter)
unique(df_prediction$peak_counter)
unique(df_experiment$created_at)
unique(df_prediction$created_at)
unique(df_experiment$updated_at)
unique(df_prediction$updated_at)
unique(df_experiment$mono_mass)
unique(df_prediction$mono_mass)
unique(df_experiment$energy_field)
unique(df_prediction$energy_field)
unique(df_experiment$collision_energy_level)
unique(df_prediction$collision_energy_level)
unique(df_experiment$ionization_mode)
unique(df_prediction$ionization_mode)
unique(df_experiment$sample_concentration_units)
unique(df_prediction$sample_concentration_units)
unique(df_experiment$sample_mass_units)
unique(df_prediction$sample_mass_units)
unique(df_experiment$predicted)
unique(df_prediction$predicted)
unique(df_experiment$structure_id)
unique(df_prediction$structure_id)
unique(df_experiment$splash_key)
unique(df_prediction$splash_key)
unique(df_experiment$chromatography_type)
unique(df_prediction$chromatography_type)
unique(df_experiment$analyzer_type)
unique(df_prediction$analyzer_type)
unique(df_experiment$ionization_type)
unique(df_prediction$ionization_type)
unique(df_experiment$charge_type)
unique(df_prediction$charge_type)
unique(df_experiment$data_source)
unique(df_prediction$data_source)
unique(df_experiment$data_source_id)
unique(df_prediction$data_source_id)
unique(df_experiment$adduct)
unique(df_prediction$adduct)
unique(df_experiment$adduct_type)
unique(df_prediction$adduct_type)
unique(df_experiment$adduct_mass)
unique(df_prediction$adduct_mass)
unique(df_experiment$database_id)
unique(df_prediction$database_id)
